
sudo: false
language: python
python: '3.5'
env:
  global:
    secure: QFh0R40nVggf2NUDfTMWlf6Ud2ELjOoiIr7kwilwXYndXUJ63A1QxOguFZQdOmQcTD0FNNNMPbTRFS8K6UYU5F6vqW+ReUkBx9Tz6U6+R3nUj36Q36gAUFvICdlQuSt9xTRCW4JYREXpxK9c6mHMOar7myupCHIB8DjY6l3ZLfXHPQmcNf2Cip5I0AXPN41r2XOQ8OPaz3MUJ+evFShBhTGxn94RhVMpdFzFjyeNN/h4pSPGV1OG+rZc3fHcled3dBkR3cdRvOYJzNBxA3UkIO1iZdMvdTnTkkXunR38RU39xbd3eErkIojwbdhbk+z9M4Ww5U7gvoQ9eYqFfXFF6Mp4nMbRC/Gu5JFJAPxRcZIE88CzmC+1NmAf6h92y4lWICV4HCD3nC3dcps9Noe02J16YA7gnmk2jLnNhLLXiXvnlbScFqsdSneT1a1PEbApkRL03bJ8ImeVVpw+6fzKNEFktuTcMhY3kvCKeumrDe+5tEHUepp5ui0Iogq6B6sUqDYr4nvrWl+X+Wrqk0Pd1yGXsE4qa3B3uvuyj5onGXjP7zjDud9n41+WivKN6J6UyEK3WV1m9GRMeYOFVhqYSbOQXAsMHzi/c4THeMn9PUtkPKo0xYD9p9AC1Qic56J3oYx0ydvKW+vyEhLegpb4rIJfCFBOwdEum2uuIpuJ4xM=
script:
- git config user.name "tuanpmt"
- git config user.email "tuanpm@live.com"
- git remote add gh-token "https://${GH_TOKEN}@github.com/microbitvn/help.microbit.vn.git"
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages
- pip install mkdocs -U
- mkdocs gh-deploy -v --clean --remote-name gh-token
